# DESHABILITADO - Usando Vercel en su lugar
# Flujo de trabajo para desplegar contenido estático en GitHub Pages
name: Desplegar contenido estático en Pages (DISABLED)

on:
  # push:
  #   branches: [ "master" ] # Cambia a tu rama principal si es diferente
  workflow_dispatch: # Solo manual

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Instalar dependencias
        run: |
          cd Frontend_Portal50
          npm install

      - name: Construir el proyecto
        run: |
          cd Frontend_Portal50
          npm run build

      - name: Subir artefacto para Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './Frontend_Portal50/dist'

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
